parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $weatherApiKey:     '%env(resolve:WEATHER_API_KEY)%'
      $weatherApiBaseUrl: '%env(resolve:WEATHER_API_BASE_URL)%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Listener\JsonResponseTransformerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }